---
# tasks file for MariadbGalera
- name: create mariadb initial pod
  kubernetes.core.k8s:
    state: present
    generate_name: pod-
    definition:
      apiVersion: v1
      kind: Pod
      spec:
        containers:
        - env:
          - name: GALERA_INIT
          - name: MYSQL_DATABASE
            value: db
          - name: MYSQL_PASSWORD
            value: pass
          - name: MYSQL_USER
            value: user
            image: "quay.io/ljavorsk/mariadb-galera-init"
            ports:
            - containerPort: 3306
              protocol: TCP
            - containerPort: 4444
              protocol: TCP
            - containerPort: 4567
              protocol: TCP
            - containerPort: 4568
              protocol: TCP
    wait_timeout: 3000
    wait_condition:
      type: Successful
      status: "True"
