---
# tasks file for MariadbGalera

- name: Create Service for all MariadbGalera Pods
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ ansible_operator_meta.name }}-service'
        namespace: '{{ ansible_operator_meta.namespace }}'
        labels:
          app: mariadbgalera
      spec:
        selector:
          app: mariadbgalera
        ports:
        - name: mariadb-database
          protocol: TCP
          port: 3306
          targetPort: 3306


- name: Create MariadbGalera Init Pod
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: '{{ ansible_operator_meta.name }}-init'
        namespace: '{{ ansible_operator_meta.namespace }}'
        labels:
          app: mariadbgalera
      spec:
        containers:
        - env:
          - name: GALERA_INIT
          - name: MYSQL_DATABASE
            value: db
          - name: MYSQL_PASSWORD
            value: pass
          - name: MYSQL_USER
            value: user
          name: mariadbgalera-init
          image: "quay.io/ljavorsk/mariadb-galera-init"
          ports:
          - containerPort: 3306
            protocol: TCP
          - containerPort: 4444
            protocol: TCP
          - containerPort: 4567
            protocol: TCP
          - containerPort: 4568
            protocol: TCP
    wait: yes
    wait_timeout: 3000
    wait_condition:
      type: Ready
      status: "True"

- name: Store info from all MariaDB Pods
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: '{{ ansible_operator_meta.namespace }}'
    label_selectors:
      - app = mariadbgalera
  register: nodesregister


- name: Create MariadbGalera Deployment for connecting nodes
  kubernetes.core.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-node'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: mariadbgalera
        template:
          metadata:
            labels:
              app: mariadbgalera
          spec:
            containers:
            - env:
              - name: CLUSTERS_IP4
                value: '{{ nodesregister.resources[0].status.podIP }}'
              - name: MYSQL_DATABASE
                value: db
              - name: MYSQL_PASSWORD
                value: pass
              - name: MYSQL_USER
                value: user
              name: mariadbgalera-node
              image: "quay.io/ljavorsk/mariadb-galera-init"
              ports:
              - containerPort: 3306
                protocol: TCP
              - containerPort: 4444
                protocol: TCP
              - containerPort: 4567
                protocol: TCP
              - containerPort: 4568
                protocol: TCP

- name: Create Galera Arbitrator Deployment
  kubernetes.core.k8s:
    definition:
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-garbd'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{garbdsize}}"
        selector:
          matchLabels:
            app: garbd
        template:
          metadata:
            labels:
              app: garbd
          spec:
            containers:
            - env:
              - name: CLUSTERS_IP4
                value: '{{ nodesregister.resources[0].status.podIP }}'
              name: garbd-node
              image: "quay.io/ljavorsk/garbd"
              ports:
              - containerPort: 4444
                protocol: TCP
              - containerPort: 4567
                protocol: TCP
              - containerPort: 4568
                protocol: TCP

