# permissions for end users to view mariadbgaleras.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mariadbgalera-viewer-role
rules:
- apiGroups:
  - ljavorsk-mariadb-operator.com
  resources:
  - mariadbgaleras
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ljavorsk-mariadb-operator.com
  resources:
  - mariadbgaleras/status
  verbs:
  - get
